Repository ArkEcosystem/swift-crypto, pull requests merged in 2019-05, with the labels that each got.

#22 feat: vendorfield increase
  CHANGELOG.md
  Crypto/Crypto/Transactions/ArkTransaction.swift
  SwiftCrypto.podspec
Labels: Complexity: Low, Type: Feature

#25 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#27 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
